/**
 * embed-plex.cjs — generate src/lib/fonts/ibmPlexArabicFontData.js
 *
 * Reads the @fontsource IBM Plex Sans Arabic woff2 subset files and emits a
 * base64 data module, mirroring cairoFontData.js. This lets the salary print /
 * PDF document embed IBM Plex Sans Arabic so the printed sheet renders with the
 * exact requested font (and correct Arabic shaping) regardless of the host.
 *
 * Run once:  node scripts/embed-plex.cjs
 */
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', 'node_modules', '@fontsource', 'ibm-plex-sans-arabic', 'files');
const OUT = path.join(__dirname, '..', 'src', 'lib', 'fonts', 'ibmPlexArabicFontData.js');

// Only the weights/subsets the salary sheet actually needs (keeps the blob lean).
const WEIGHTS = [400, 600, 700];
const SUBSETS = ['arabic', 'latin'];

const data = {};
for (const w of WEIGHTS) {
  for (const s of SUBSETS) {
    const file = path.join(SRC, `ibm-plex-sans-arabic-${s}-${w}-normal.woff2`);
    if (!fs.existsSync(file)) {
      console.warn('missing', file);
      continue;
    }
    data[`${s}_${w}`] = fs.readFileSync(file).toString('base64');
  }
}

const header =
`/**
 * ibmPlexArabicFontData.js — AUTO-GENERATED by scripts/embed-plex.cjs
 * Base64 woff2 subsets of IBM Plex Sans Arabic (@fontsource) for embedding in
 * the self-contained salary print / PDF document. Do not edit by hand.
 */
export const PLEX_FONTS = `;

fs.writeFileSync(OUT, header + JSON.stringify(data) + ';\n');
const kb = Math.round(fs.statSync(OUT).size / 1024);
console.log(`wrote ${OUT} (${kb} KB, ${Object.keys(data).length} faces)`);
